feat: add drainDelay configuration property
kubereboot/charts pull request #62
Opened 2023-11-16 18:32 UTC by MerlinDMC

This PR adds the `drainDelay` configuration property provided by https://github.com/kubereboot/kured/pull/852

2023-11-18 14:15 UTC, ckotzbauer requested changes
Thanks, please also add the new parameter to the chart's README and bump the `version` field in the `Chart.yaml`.

2023-11-20 07:00 UTC, MerlinDMC commented
Sorry for the delay.
I've overlooked the list of properties in the README (probably got used to pre-commit hooks to well by now)

2023-11-20 17:02 UTC, ckotzbauer approved these changes

2023-12-11 18:59 UTC, jackfrancis approved these changes
lgtm

2023-12-11 18:59 UTC, merged